cask_args appdir: "/Applications"

# Tap Homebrew
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask-fonts"

cask "firefox"
cask "google-chrome"
cask "chromedriver"
cask "docker"
cask "hammerspoon"
cask "gimp"
cask "inkscape"
cask "bitwarden"
cask "1password"
cask "1password-cli"
cask "optimage"
cask "pomotroid"
cask "kitty"
cask "karabiner-elements"
cask "sequel-ace"
cask "activitywatch"

cask "font-victor-mono-nerd-font"
cask "font-fira-code-nerd-font"

# System
brew "coreutils"
# slightly more up to date versions of things
brew "openssh"
brew "rsync"
brew "git"
brew "curl"
brew "wget"
brew "less"
brew "exa"
brew "openjdk"
brew "asdf"

brew "neovim"
brew "fish"
brew "saulpw/vd/visidata"
brew "yqrashawn/goku/goku"
brew "ripgrep"
brew "fzf"
brew "git-delta"
brew "fd"
brew "w3m"
brew "tealdeer"
brew "screen"
brew "ssh-copy-id"
brew "curlie"
brew "imagemagick"
brew "optipng"
brew "ffmpeg"
brew "xz"
brew "p7zip"
brew "mutagen-io/mutagen/mutagen"

brew "hub"
brew "ghq"

# JSON
brew "jq"
brew "jo"

