# Monokai Pro (Machine)
# Ported from loctvl842/monokai-pro.nvim machine palette

background            #273136
foreground            #f2fffc

cursor                #f2fffc
cursor_text_color     #273136

selection_background  #f2fffc
selection_foreground  #273136

url_color             #7cd5f1

active_tab_background   #545f62
active_tab_foreground   #273136
active_border_color     #7cd5f1

inactive_tab_background #273136
inactive_tab_foreground #545f62
inactive_border_color   #545f62

# 16 Color Space

# black
color0  #273136
color8  #545f62

# red
color1  #ff6d7e
color9  #ff6d7e

# green
color2  #a2e57b
color10 #a2e57b

# yellow
color3  #ffed72
color11 #ffed72

# blue (orange in Monokai Pro)
color4  #ffb270
color12 #ffb270

# magenta
color5  #baa0f8
color13 #baa0f8

# cyan
color6  #7cd5f1
color14 #7cd5f1

# white
color7  #f2fffc
color15 #f2fffc
