# vim:foldmethod=marker

#: Fonts {{{

font_size 15.0

# Nerd Fonts v3 symbol map (font version 3.2.1)
# troubleshoot with: kitty --debug-font-fallback
symbol_map U+e000-U+e00a,U+e0a0-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b1,U+e700-U+e7c5,U+ea60-U+ebeb,U+ed00-U+efc1,U+f000-U+f2ff,U+f300-U+f372,U+f400-U+f533,U+f0001-U+f1af0 Symbols Nerd Font

# Checkmark, star and other glyphs used by tools like phpactor/symfony console
symbol_map U+2713,U+2714,U+2605,U+21B5,U+25B8 Menlo

#: }}}

#: Bell {{{

visual_bell_duration 0.01

#: }}}

#: Scrollback {{{

pixel_scroll yes

#: }}}

#: Advanced {{{

shell /opt/homebrew/bin/fish

allow_remote_control yes
listen_on unix:/tmp/mykitty

clipboard_control write-clipboard write-primary

#: }}}

#: macOS {{{

macos_option_as_alt yes
macos_thicken_font 0
macos_show_window_title_in menubar

#: }}}

#: Keyboard shortcuts {{{

# Disable accidental tab/window closing
map kitty_mod+q     no_op
map cmd+w           no_op
map shift+cmd+w     no_op

map kitty_mod+h previous_tab
map kitty_mod+l next_tab

# Hints
map kitty_mod+e         open_url_with_hints
map kitty_mod+p>f       kitten hints --type path --program -
map kitty_mod+p>shift+f kitten hints --type path
map kitty_mod+p>l       kitten hints --type line --program -
map kitty_mod+p>w       kitten hints --type word --program -
map kitty_mod+p>h       kitten hints --type hash --program -
map kitty_mod+p>n       kitten hints --type linenum
map kitty_mod+p>y       kitten hints --type hyperlink

#: }}}

# BEGIN_KITTY_THEME
# Monokai Pro Machine
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family='Victor Mono' postscript_name=VictorMono-Medium
bold_font        family='Victor Mono' style=SemiBold
italic_font      family='Victor Mono' postscript_name=VictorMono-MediumItalic
bold_italic_font family='Victor Mono' postscript_name=VictorMono-BoldOblique
# END_KITTY_FONTS
